language: zh
pipeline:
- name: SpacyNLP
  model: zh_core_web_sm
- name: SpacyTokenizer
  intent_tokenization_flag: false
  intent_split_symbol: _
  token_pattern: None
- name: SpacyFeaturizer
  pooling: mean
- name: DIETClassifier
  epochs: 100
- name: SpacyEntityExtractor
policies:
- name: FallbackPolicy
  nlu_threshold: 0.75
- name: AugmentedMemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 20
