language: zh
pipeline:
- name: SpacyNLP
  model: zh_core_web_sm
- name: SpacyTokenizer
  intent_tokenization_flag: false
  intent_split_symbol: _
  token_pattern: None
- name: RegexFeaturizer
- name: SpacyFeaturizer
  pooling: mean
- name: DIETClassifier
- name: SpacyEntityExtractor
- name: ResponseSelector
  retrieval_intent: chitchat
policies:
- name: FallbackPolicy
  nlu_threshold: 0.5
  fallback_action_name: action_default_fallback
- name: AugmentedMemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 20
