language: zh
pipeline:
- name: SpacyNLP
  model: zh_core_web_sm
- name: SpacyTokenizer
  intent_tokenization_flag: false
  intent_split_symbol: _
  token_pattern: None
- name: RegexFeaturizer
- name: SpacyFeaturizer
  pooling: mean
# for entity extractor
- name: SpacyEntityExtractor
- name: DIETClassifier
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: chitchat
- name: ResponseSelector
  retrieval_intent: faq
policies:
- name: FallbackPolicy
  nlu_threshold: 0.2
  core_threshold: 0.2
  ambiguity_threshold: 0.05
  fallback_action_name: action_default_fallback
- name: FormPolicy
- name: MappingPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 20
